%define		kdeplasmaver	5.5.4
%define		qtver		5.3.2
%define		kpname		breeze-gtk
Summary:	Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
Name:		kp5-%{kpname}
Version:	5.5.4
Release:	1
License:	GPL v2+/LGPL v2.1+
Group:		X11/Libraries
Source0:	http://download.kde.org/stable/plasma/%{kdeplasmaver}/%{kpname}-%{version}.tar.xz
# Source0-md5:	d7bcd2d966533519ca7bd7c8d83f2490
URL:		http://www.kde.org/
BuildRequires:	Qt5Core-devel >= %{qtver}
BuildRequires:	Qt5DBus-devel
BuildRequires:	Qt5Gui-devel
BuildRequires:	Qt5Widgets-devel
BuildRequires:	Qt5X11Extras-devel
BuildRequires:	Qt5Xml-devel
BuildRequires:	cmake >= 2.8.12
BuildRequires:	gettext-devel
BuildRequires:	hardlink >= 1.0-3
BuildRequires:	kf5-attica-devel
BuildRequires:	kf5-extra-cmake-modules >= 1.4.0
BuildRequires:	kf5-frameworkintegration-devel
BuildRequires:	kf5-kauth-devel
BuildRequires:	kf5-kcmutils-devel
BuildRequires:	kf5-kcodecs-devel
BuildRequires:	kf5-kconfig-devel
BuildRequires:	kf5-kconfigwidgets-devel
BuildRequires:	kf5-kcoreaddons-devel
BuildRequires:	kf5-kguiaddons-devel
BuildRequires:	kf5-ki18n-devel
BuildRequires:	kf5-kiconthemes-devel
BuildRequires:	kf5-kservice-devel
BuildRequires:	kf5-kwidgetsaddons-devel
BuildRequires:	kf5-kwindowsystem-devel
BuildRequires:	kp5-kdecoration-devel
BuildRequires:	libstdc++-devel
BuildRequires:	pkgconfig
BuildRequires:	qt5-build >= %{qtver}
BuildRequires:	qt5-qmake
BuildRequires:	rpmbuild(macros) >= 1.596
BuildRequires:	tar >= 1:1.22
BuildRequires:	xz
Requires:	%{kpname}-cursor-theme = %{version}-%{release}
Requires:	%{kpname}-icon-theme = %{version}-%{release}
Requires:	gtk-update-icon-cache
Requires:	hicolor-icon-theme
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Artwork, styles and assets for the Breeze visual style for the Plasma
Desktop.

%package -n %{kpname}-icon-theme
Summary:	Breeze icon theme
Summary(pl.UTF-8):	Breeze Motyw ikon
Group:		Themes
Requires:	gtk-update-icon-cache
Requires:	hicolor-icon-theme
Conflicts:	kp5-breeze < 5.4.0-5
%if "%{_rpmversion}" >= "5"
BuildArch:	noarch
%endif

%description -n %{kpname}-icon-theme
Breeze is an icon theme.

%description -n %{kpname}-icon-theme -l pl.UTF-8
Breeze to motyw ikon.

%package -n %{kpname}-cursor-theme
Summary:	Breeze cursor theme
Group:		Themes
Conflicts:	breeze-icon-theme < 5.4.0-7
Conflicts:	kp5-breeze < 5.4.0-5
%if "%{_rpmversion}" >= "5"
BuildArch:	noarch
%endif

%description -n %{kpname}-cursor-theme
Breeze cursor theme.

%prep
%setup -q -n %{kpname}-%{version}

%build
install -d build
cd build
%cmake \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
	..
%{__make}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} -C build install \
	DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%post
%update_icon_cache hicolor

%postun
%update_icon_cache hicolor

%files
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/kconf_update_bin/gtkbreeze5.5
%{_datadir}/kconf_update/gtkbreeze5.5.upd
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-down-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-down-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-down-small-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-down-small-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-down-small.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-down.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-left-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-left-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-left-small-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-left-small-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-left-small.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-left.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-right-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-right-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-right-small-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-right-small-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-right-small.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-right.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-up-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-up-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-up-small-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-up-small-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-up-small.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/arrow-up.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/menu-arrow-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/menu-arrow-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Arrows/menu-arrow.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Buttons/button-default.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Buttons/button-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Buttons/button-normal.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Buttons/button-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Buttons/button-pressed.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/checkbox-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/checkbox-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-checkbox-checked-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-checkbox-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-checkbox-unchecked-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-checkbox-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-option-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-option-checked-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-option-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-option-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-option-unchecked-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/menu-option-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/option-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/option-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/option-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Check-Radio/option-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Entry/entry-border-active-bg.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Entry/entry-border-bg.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Entry/entry-border-disabled-bg.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Expanders/minus.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Expanders/plus.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Handles/handle-h.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Handles/handle-v.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Lines/line-h.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Lines/line-v.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Lines/menu-line-h.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Menubar/menu-frame.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Menubar/menubar-button.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Others/null.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Others/tree-header.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/ProgressBar/bar.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/ProgressBar/trough.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Range/slider-horiz-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Range/slider-horiz.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Range/slider-vert-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Range/slider-vert.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Range/trough-horizontal.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Range/trough-vertical.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-horiz-active.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-horiz-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-horiz-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-horiz.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-vert-active.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-vert-insens.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-vert-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/slider-scrollbar-vert.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/trough-scrollbar-horiz.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Scrollbars/trough-scrollbar-vert.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Shadows/frame-gap-end.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Shadows/frame-gap-start.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Shadows/frame.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Spin/down-background-disable.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Spin/down-background.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Spin/up-background-disable.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Spin/up-background.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/notebook-gap-horiz.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/notebook-gap-vert.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/notebook.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-bottom-active.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-bottom-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-bottom.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-left-active.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-left-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-left.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-right-active.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-right-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-right.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-top-active.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-top-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Tabs/tab-top.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Toolbar/toolbar-bg.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Toolbar/toolbutton-normal.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Toolbar/toolbutton-prelight.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Toolbar/toolbutton-pressed.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/Toolbar/toolbutton-toggled.png
%{_datadir}/themes/Breeze-Dark/gtk-2.0/assets.svg
%{_datadir}/themes/Breeze-Dark/gtk-2.0/assets.txt
%{_datadir}/themes/Breeze-Dark/gtk-2.0/gtkrc
%{_datadir}/themes/Breeze-Dark/gtk-2.0/render-assets.sh
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-active-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-active-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-backdrop-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-backdrop-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-active-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-active-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-hover-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-hover-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-checked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-hover-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-hover-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-mixed@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-selectionmode.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-selectionmode@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/checkbox-unchecked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-checked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-mixed@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/radio-unchecked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-overlay-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-overlay-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-overlay.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal-overlay@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-horizontal@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-overlay-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-overlay-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-overlay.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-overlay@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider-rtl@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-slider@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-horizontal-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-horizontal-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-horizontal.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-horizontal@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-rtl-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-rtl-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-rtl.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough-rtl@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/scrollbar-trough@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-checked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-mixed@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-checkbox-unchecked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-checked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-mixed@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/selected-radio-unchecked@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-above@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-horz-scale-has-marks-below@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-above@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-active-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-active-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive-dark.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive-dark@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/slider-vert-scale-has-marks-below@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-close@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-maximize@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize-active.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize-active@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize-backdrop.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize-backdrop@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize-hover.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize-hover@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/assets/titlebutton-minimize@2.png
%{_datadir}/themes/Breeze-Dark/gtk-3.0/gtk.css
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-down-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-down-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-down-small-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-down-small-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-down-small.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-down.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-left-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-left-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-left-small-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-left-small-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-left-small.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-left.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-right-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-right-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-right-small-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-right-small-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-right-small.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-right.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-up-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-up-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-up-small-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-up-small-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-up-small.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/arrow-up.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/menu-arrow-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/menu-arrow-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Arrows/menu-arrow.png
%{_datadir}/themes/Breeze/gtk-2.0/Buttons/button-default.png
%{_datadir}/themes/Breeze/gtk-2.0/Buttons/button-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Buttons/button-normal.png
%{_datadir}/themes/Breeze/gtk-2.0/Buttons/button-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Buttons/button-pressed.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/checkbox-checked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/checkbox-unchecked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-checkbox-checked-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-checkbox-checked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-checkbox-unchecked-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-checkbox-unchecked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-option-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-option-checked-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-option-checked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-option-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-option-unchecked-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/menu-option-unchecked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/option-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/option-checked.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/option-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-2.0/Check-Radio/option-unchecked.png
%{_datadir}/themes/Breeze/gtk-2.0/Entry/entry-border-active-bg.png
%{_datadir}/themes/Breeze/gtk-2.0/Entry/entry-border-bg.png
%{_datadir}/themes/Breeze/gtk-2.0/Entry/entry-border-disabled-bg.png
%{_datadir}/themes/Breeze/gtk-2.0/Expanders/minus.png
%{_datadir}/themes/Breeze/gtk-2.0/Expanders/plus.png
%{_datadir}/themes/Breeze/gtk-2.0/Handles/handle-h.png
%{_datadir}/themes/Breeze/gtk-2.0/Handles/handle-v.png
%{_datadir}/themes/Breeze/gtk-2.0/Lines/line-h.png
%{_datadir}/themes/Breeze/gtk-2.0/Lines/line-v.png
%{_datadir}/themes/Breeze/gtk-2.0/Lines/menu-line-h.png
%{_datadir}/themes/Breeze/gtk-2.0/Menubar/menu-frame.png
%{_datadir}/themes/Breeze/gtk-2.0/Menubar/menubar-button.png
%{_datadir}/themes/Breeze/gtk-2.0/Others/null.png
%{_datadir}/themes/Breeze/gtk-2.0/Others/tree-header.png
%{_datadir}/themes/Breeze/gtk-2.0/ProgressBar/bar.png
%{_datadir}/themes/Breeze/gtk-2.0/ProgressBar/trough.png
%{_datadir}/themes/Breeze/gtk-2.0/Range/slider-horiz-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Range/slider-horiz.png
%{_datadir}/themes/Breeze/gtk-2.0/Range/slider-vert-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Range/slider-vert.png
%{_datadir}/themes/Breeze/gtk-2.0/Range/trough-horizontal.png
%{_datadir}/themes/Breeze/gtk-2.0/Range/trough-vertical.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-horiz-active.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-horiz-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-horiz-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-horiz.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-vert-active.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-vert-insens.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-vert-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/slider-scrollbar-vert.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/trough-scrollbar-horiz.png
%{_datadir}/themes/Breeze/gtk-2.0/Scrollbars/trough-scrollbar-vert.png
%{_datadir}/themes/Breeze/gtk-2.0/Shadows/frame-gap-end.png
%{_datadir}/themes/Breeze/gtk-2.0/Shadows/frame-gap-start.png
%{_datadir}/themes/Breeze/gtk-2.0/Shadows/frame.png
%{_datadir}/themes/Breeze/gtk-2.0/Spin/down-background-disable.png
%{_datadir}/themes/Breeze/gtk-2.0/Spin/down-background.png
%{_datadir}/themes/Breeze/gtk-2.0/Spin/up-background-disable.png
%{_datadir}/themes/Breeze/gtk-2.0/Spin/up-background.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/notebook-gap-horiz.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/notebook-gap-vert.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/notebook.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-bottom-active.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-bottom.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-left-active.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-left.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-right-active.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-right.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-top-active.png
%{_datadir}/themes/Breeze/gtk-2.0/Tabs/tab-top.png
%{_datadir}/themes/Breeze/gtk-2.0/Toolbar/toolbar-bg.png
%{_datadir}/themes/Breeze/gtk-2.0/Toolbar/toolbutton-normal.png
%{_datadir}/themes/Breeze/gtk-2.0/Toolbar/toolbutton-prelight.png
%{_datadir}/themes/Breeze/gtk-2.0/Toolbar/toolbutton-pressed.png
%{_datadir}/themes/Breeze/gtk-2.0/Toolbar/toolbutton-toggled.png
%{_datadir}/themes/Breeze/gtk-2.0/assets.svg
%{_datadir}/themes/Breeze/gtk-2.0/assets.txt
%{_datadir}/themes/Breeze/gtk-2.0/gtkrc
%{_datadir}/themes/Breeze/gtk-2.0/render-assets.sh
%{_datadir}/themes/Breeze/gtk-3.0/_colors-public.scss
%{_datadir}/themes/Breeze/gtk-3.0/_colors.scss
%{_datadir}/themes/Breeze/gtk-3.0/_common.scss
%{_datadir}/themes/Breeze/gtk-3.0/_drawing.scss
%{_datadir}/themes/Breeze/gtk-3.0/assets.svg
%{_datadir}/themes/Breeze/gtk-3.0/assets.txt
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-active-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-active-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-backdrop-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-backdrop-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-active-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-active-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-hover-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-hover-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-checked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-hover-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-hover-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-mixed@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-selectionmode.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-selectionmode@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/checkbox-unchecked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-checked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-mixed@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/radio-unchecked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-overlay-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-overlay-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-overlay.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal-overlay@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-horizontal@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-overlay-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-overlay-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-overlay.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-overlay@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider-rtl@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-slider@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-horizontal-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-horizontal-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-horizontal.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-horizontal@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-rtl-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-rtl-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-rtl.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough-rtl@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/scrollbar-trough@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-checked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-mixed@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-checkbox-unchecked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-checked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-mixed@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/selected-radio-unchecked@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-above@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-horz-scale-has-marks-below@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-above@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-active-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-active-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive-dark.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive-dark@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below-insensitive@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/slider-vert-scale-has-marks-below@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-close@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-maximize@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize-active.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize-active@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize-backdrop.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize-backdrop@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize-hover.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize-hover@2.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize.png
%{_datadir}/themes/Breeze/gtk-3.0/assets/titlebutton-minimize@2.png
%{_datadir}/themes/Breeze/gtk-3.0/gtk-contained-dark.css
%{_datadir}/themes/Breeze/gtk-3.0/gtk-contained.css
%{_datadir}/themes/Breeze/gtk-3.0/gtk-contained.scss
%{_datadir}/themes/Breeze/gtk-3.0/gtk-dark.css
%{_datadir}/themes/Breeze/gtk-3.0/gtk.css
%{_datadir}/themes/Breeze/gtk-3.0/gtk.css.map
%{_datadir}/themes/Breeze/gtk-3.0/render-assets.sh
